version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    restart: unless-stopped

  dashboard-service:
    build: ./dashboard-service
    container_name: dashboard-service
    ports:
      - "5001:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    restart: unless-stopped

networks:
  default:
    name: enterprise-network
