[pytest]
pythonpath =
    api-gateway
    auth-service
    dashboard-service

testpaths =
    api-gateway/tests
    auth-service/tests
    dashboard-service/tests

norecursedirs =
    .git
    .venv
    venv
    actions-runner
    node_modules
