sonar.projectKey=enterprise-devops-platform
sonar.projectName=enterprise-devops-platform
sonar.sourceEncoding=UTF-8

sonar.sources=frontend,api-gateway,auth-service,dashboard-service

sonar.python.version=3.11

sonar.python.coverage.reportPaths=auth-service/coverage.xml
