apiVersion: v1
kind: Service

metadata:
  name: api-gateway-service
  namespace: {{ .Values.namespace }}

  labels:
    app: api-gateway
    project: enterprise-devops-platform
    environment: {{ .Values.global.environment | lower }}


spec:

  selector:

    app: api-gateway


  ports:

  - protocol: TCP

    port: {{ .Values.services.apiGateway.port }}

    targetPort: {{ .Values.services.apiGateway.targetPort }}


  type: ClusterIP
