apiVersion: v1
kind: Service

metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}

  labels:
    app: auth-service
    project: enterprise-devops-platform
    environment: {{ .Values.global.environment | lower }}


spec:

  selector:

    app: auth-service


  ports:

  - protocol: TCP

    port: {{ .Values.services.auth.port }}

    targetPort: {{ .Values.services.auth.targetPort }}


  type: ClusterIP
