apiVersion: v1
kind: ConfigMap

metadata:
  name: enterprise-config
  namespace: {{ .Values.namespace }}

data:

  ENVIRONMENT: {{ .Values.global.environment | quote }}

  DATABASE_HOST: {{ .Values.database.host | quote }}

  DATABASE_PORT: {{ .Values.database.port | quote }}

  DATABASE_NAME: {{ .Values.database.name | quote }}

  DATABASE_USER: {{ .Values.database.user | quote }}
