apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}

  labels:
    app: frontend
    project: enterprise-devops-platform
    environment: {{ .Values.global.environment | lower }}


spec:

  selector:

    app: frontend


  ports:

  - protocol: TCP

    port: {{ .Values.services.frontend.port }}

    targetPort: {{ .Values.services.frontend.targetPort }}


  type: ClusterIP
