apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: {{ .Values.namespace }}

  labels:
    app: postgres
    project: enterprise-devops-platform

spec:

  replicas: {{ .Values.postgres.replicas }}

  selector:

    matchLabels:
      app: postgres


  template:

    metadata:

      labels:
        app: postgres


    spec:

      containers:

      - name: postgres

        image: {{ .Values.postgres.image }}

        ports:

        - containerPort: 5432


        envFrom:

        - secretRef:
            name: postgres-secret


        volumeMounts:

        - name: postgres-storage

          mountPath: /var/lib/postgresql/data


      volumes:

      - name: postgres-storage

        persistentVolumeClaim:

          claimName: postgres-pvc
