apiVersion: v1
kind: Secret

metadata:
  name: enterprise-secrets
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:

  SECRET_KEY: "change-this-secret-key"

  JWT_SECRET_KEY: "change-this-jwt-secret-key"
