apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: enterprise-dev

type: Opaque

stringData:

  POSTGRES_DB: enterprise_db

  POSTGRES_USER: enterprise_user

  POSTGRES_PASSWORD: enterprise_password
