name: Enterprise CD Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish-images:
    name: Publish Docker Images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - service: frontend
            dockerfile: ./frontend/Dockerfile

          - service: api-gateway
            dockerfile: ./api-gateway/Dockerfile

          - service: auth-service
            dockerfile: ./auth-service/Dockerfile

          - service: dashboard-service
            dockerfile: ./dashboard-service/Dockerfile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
